.TH xlsview 1  
.SH NAME
xlsview \- graphical front-end for xls2csv(1)
.SH SYNOPSIS

.BR xlsview
.I files

.SH DESCRIPTION

.B xlsview
is a front-end for the 
.BR xls2csv (1)
program.  It tries to create an HTML page from the spreadsheet provided as
a command line argument, and open a browser to view it.  See the manpage for 
.BR xls2csv (1)
for more information.

.SH AUTHOR

This incredibly lame man page was written by Bdale Garbee for Debian GNU/Linux.
